2024-04-11 14:22:15 INFO  [org.apache.camel.quarkus.core.CamelBootstrapRecorder] (Quarkus Main Thread) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2024-04-11 14:22:15 INFO  [org.apache.camel.main.MainSupport] (Quarkus Main Thread) Apache Camel (Main) 3.20.1 is starting
2024-04-11 14:22:15 INFO  [org.apache.camel.main.BaseMainSupport] (Quarkus Main Thread) Auto-configuration summary
2024-04-11 14:22:16 INFO  [org.apache.camel.main.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] camel.component.kafka.brokers=localhost:9092
2024-04-11 14:22:16 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Quarkus Main Thread) Apache Camel 3.20.1 (camel-2) is starting
2024-04-11 14:22:17 INFO  [org.apache.camel.component.kafka.KafkaConsumer] (Quarkus Main Thread) Starting Kafka consumer on topic: NSP.fresh.payment.applicant_sms_logs with breakOnFirstError: false
2024-04-11 14:22:17 INFO  [org.apache.camel.component.kafka.KafkaConsumer] (Quarkus Main Thread) Starting Kafka consumer on topic: NSP.fresh.payment.applicant_sms_logs with breakOnFirstError: false
2024-04-11 14:22:17 INFO  [org.apache.camel.main.BaseMainSupport] (Quarkus Main Thread) Property-placeholders summary
2024-04-11 14:22:17 INFO  [org.apache.camel.main.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] kafka.topic.name0=NSP.fresh.payment.applicant_sms_logs
2024-04-11 14:22:17 INFO  [org.apache.camel.main.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] host.port.elastic=localhost:9200
2024-04-11 14:22:17 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Connecting Kafka consumer thread ID NSP.fresh.payment.applicant_sms_logs-Thread 0 with poll timeout of 5000 ms
2024-04-11 14:22:17 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Quarkus Main Thread) Routes startup (started:2)
2024-04-11 14:22:17 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Quarkus Main Thread)     Started FromKafkareg1 (kafka://NSP.fresh.payment.applicant_sms_logs)
2024-04-11 14:22:17 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Quarkus Main Thread)     Started ProcessBeneficiary (kafka://NSP.fresh.payment.applicant_sms_logs)
2024-04-11 14:22:17 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Camel (camel-2) thread #2 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Connecting Kafka consumer thread ID NSP.fresh.payment.applicant_sms_logs-Thread 0 with poll timeout of 5000 ms
2024-04-11 14:22:17 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Quarkus Main Thread) Apache Camel 3.20.1 (camel-2) started in 1s480ms (build:0ms init:733ms start:747ms)
2024-04-11 14:22:17 INFO  [io.quarkus.scheduler.runtime.SimpleScheduler] (Quarkus Main Thread) No scheduled business methods found - Simple scheduler will not be started
2024-04-11 14:22:17 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.16.10.Final) started in 12.492s. Listening on: http://localhost:9090
2024-04-11 14:22:17 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-04-11 14:22:17 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, camel-activemq, camel-attachments, camel-bean, camel-core, camel-crypto, camel-direct, camel-freemarker, camel-http, camel-jackson, camel-jms, camel-js-dsl, camel-kafka, camel-log, camel-microprofile-health, camel-platform-http, camel-rest, camel-seda, camel-sql, camel-timer, cdi, elasticsearch-rest-client, freemarker, hibernate-orm, hibernate-orm-panache, jdbc-h2, jdbc-postgresql, kafka-client, kubernetes-client, micrometer, narayana-jta, opentelemetry, opentelemetry-otlp-exporter, rest-client, rest-client-jackson, resteasy, resteasy-jackson, scheduler, security, smallrye-context-propagation, smallrye-health, smallrye-openapi, swagger-ui, vertx]
2024-04-11 14:22:17 INFO  [io.quarkus.deployment.dev.RuntimeUpdatesProcessor] (Timer-0) Live reload total time: 52.001s 
2024-04-11 14:22:17 INFO  [io.quarkus.deployment.dev.RuntimeUpdatesProcessor] (Timer-0) Live reload took more than 4 seconds, you may want to enable instrumentation based reload (quarkus.live-reload.instrumentation=true). This allows small changes to take effect without restarting Quarkus.
2024-04-11 14:22:18 INFO  [org.apache.camel.component.kafka.consumer.support.classic.AssignmentAdapterHelper] (Camel (camel-2) thread #2 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Using NO-OP resume strategy
2024-04-11 14:22:18 INFO  [org.apache.camel.component.kafka.consumer.support.classic.AssignmentAdapterHelper] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Using NO-OP resume strategy
2024-04-11 14:22:18 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Camel (camel-2) thread #2 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Subscribing NSP.fresh.payment.applicant_sms_logs-Thread 0 to topic NSP.fresh.payment.applicant_sms_logs
2024-04-11 14:22:18 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Subscribing NSP.fresh.payment.applicant_sms_logs-Thread 0 to topic NSP.fresh.payment.applicant_sms_logs
2024-04-11 14:22:26 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240137, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":1}, kafka.OFFSET=0, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240137, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:26 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":1,"application_id":"application_id_1","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36720960\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36720960,"xmin":null},"op":"c","ts_ms":1712825238940,"transaction":null}"
2024-04-11 14:22:27 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000000 on ExchangeId: 945101F3717ADC4-0000000000000000). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40429988

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000000]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240140, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":2}, kafka.OFFSET=1, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240140, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":2,"application_id":"application_id_2","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36721240\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36721240,"xmin":null},"op":"c","ts_ms":1712825238957,"transaction":null}"
2024-04-11 14:22:27 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000001 on ExchangeId: 945101F3717ADC4-0000000000000001). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40430069

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000001]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240140, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":3}, kafka.OFFSET=2, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240140, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":3,"application_id":"application_id_3","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36721424\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36721424,"xmin":null},"op":"c","ts_ms":1712825238958,"transaction":null}"
2024-04-11 14:22:27 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000002 on ExchangeId: 945101F3717ADC4-0000000000000002). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40430251

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000002]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240141, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":4}, kafka.OFFSET=3, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240141, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":4,"application_id":"application_id_4","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36721608\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36721608,"xmin":null},"op":"c","ts_ms":1712825238958,"transaction":null}"
2024-04-11 14:22:27 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000003 on ExchangeId: 945101F3717ADC4-0000000000000003). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40430387

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000003]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240141, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":5}, kafka.OFFSET=4, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240141, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":5,"application_id":"application_id_5","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36721792\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36721792,"xmin":null},"op":"c","ts_ms":1712825238959,"transaction":null}"
2024-04-11 14:22:27 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000004 on ExchangeId: 945101F3717ADC4-0000000000000004). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40430418

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000004]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240142, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":6}, kafka.OFFSET=5, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240142, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":6,"application_id":"application_id_6","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36721976\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36721976,"xmin":null},"op":"c","ts_ms":1712825238959,"transaction":null}"
2024-04-11 14:22:27 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:27 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000005 on ExchangeId: 945101F3717ADC4-0000000000000005). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40430472

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000005]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240143, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":7}, kafka.OFFSET=6, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240143, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:27 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":7,"application_id":"application_id_7","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36722160\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36722160,"xmin":null},"op":"c","ts_ms":1712825238960,"transaction":null}"
2024-04-11 14:22:28 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:28 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000006 on ExchangeId: 945101F3717ADC4-0000000000000006). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40430809

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:28 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000006]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240143, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":8}, kafka.OFFSET=7, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240143, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":8,"application_id":"application_id_8","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36722344\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36722344,"xmin":null},"op":"c","ts_ms":1712825238960,"transaction":null}"
2024-04-11 14:22:28 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:28 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000007 on ExchangeId: 945101F3717ADC4-0000000000000007). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40431464

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:28 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000007]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240144, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":9}, kafka.OFFSET=8, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240144, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":9,"application_id":"application_id_9","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36722528\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36722528,"xmin":null},"op":"c","ts_ms":1712825238961,"transaction":null}"
2024-04-11 14:22:28 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:28 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000008 on ExchangeId: 945101F3717ADC4-0000000000000008). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40431612

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:28 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000008]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{CamelMessageTimestamp=1712825240144, kafka.HEADERS=RecordHeaders(headers = [], isReadOnly = false), kafka.KEY={"serial_no":10}, kafka.OFFSET=9, kafka.PARTITION=0, kafka.TIMESTAMP=1712825240144, kafka.TOPIC=NSP.fresh.payment.applicant_sms_logs}"
2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Received : "{"before":null,"after":{"serial_no":10,"application_id":"application_id_10","sms_text":null,"sms_delivered_on":null,"sms_gateway_remarks":"accepted","nsp_scheme_id":3024,"agency_id":null,"sms_type":null,"sms_status":"accepted","sms_job_id":null,"elastic_time":1712825238191573},"source":{"version":"2.2.1.Final","connector":"postgresql","name":"NSP.fresh","ts_ms":1712825238208,"snapshot":"false","db":"nsp_fresh","sequence":"[\"36562304\",\"36722712\"]","schema":"payment","table":"applicant_sms_logs","txId":19783,"lsn":36722712,"xmin":null},"op":"c","ts_ms":1712825238961,"transaction":null}"
2024-04-11 14:22:28 ERROR [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:28 INFO  [FromKafkareg1] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2024-04-11 14:22:29 ERROR [org.apache.camel.processor.errorhandler.DefaultErrorHandler] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Failed delivery for (MessageId: 945101F3717ADC4-0000000000000009 on ExchangeId: 945101F3717ADC4-0000000000000009). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]. Processed by failure processor: FatalFallbackErrorHandler[null]

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         FromKafkareg1/FromKafkareg1    from[kafka://NSP.fresh.payment.applicant_sms_logs?     40431711

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:22:29 WARN  [org.apache.camel.component.kafka.KafkaConsumer] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Error during processing. Exchange[945101F3717ADC4-0000000000000009]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:68)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessor.processExchange(KafkaRecordProcessor.java:110)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processRecord(KafkaRecordProcessorFacade.java:125)
	at org.apache.camel.component.kafka.consumer.support.KafkaRecordProcessorFacade.processPolledRecords(KafkaRecordProcessorFacade.java:78)
	at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:328)
	at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.Error: Unresolved compilation problems: 
	ProcessBeneficiary cannot be resolved to a type
	ProcessBeneficiary cannot be resolved to a type

	at org.quarkus.GreetingResource.process(GreetingResource.java:69)
	at org.quarkus.GreetingResource_Subclass.process$$superforward1(Unknown Source)
	at org.quarkus.GreetingResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.quarkus.GreetingResource_Subclass.process(Unknown Source)
	at org.quarkus.GreetingResource_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	... 18 more

2024-04-11 14:24:04 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Shutdown thread) Apache Camel 3.20.1 (camel-2) is shutting down
2024-04-11 14:24:04 INFO  [org.apache.camel.component.kafka.KafkaConsumer] (Shutdown thread) Stopping Kafka consumer on topic: NSP.fresh.payment.applicant_sms_logs
2024-04-11 14:24:04 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Shutdown thread) Waiting up to 30000 milliseconds for the processing to finish
2024-04-11 14:24:09 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Camel (camel-2) thread #2 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Terminating KafkaConsumer thread NSP.fresh.payment.applicant_sms_logs-Thread 0 receiving from topic NSP.fresh.payment.applicant_sms_logs
2024-04-11 14:24:11 INFO  [org.apache.camel.component.kafka.KafkaConsumer] (Shutdown thread) Stopping Kafka consumer on topic: NSP.fresh.payment.applicant_sms_logs
2024-04-11 14:24:11 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Shutdown thread) Waiting up to 30000 milliseconds for the processing to finish
2024-04-11 14:24:14 INFO  [org.apache.camel.component.kafka.KafkaFetchRecords] (Camel (camel-2) thread #1 - KafkaConsumer[NSP.fresh.payment.applicant_sms_logs]) Terminating KafkaConsumer thread NSP.fresh.payment.applicant_sms_logs-Thread 0 receiving from topic NSP.fresh.payment.applicant_sms_logs
2024-04-11 14:24:15 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Shutdown thread) Routes stopped (stopped:2)
2024-04-11 14:24:15 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Shutdown thread)     Stopped FromKafkareg1 (kafka://NSP.fresh.payment.applicant_sms_logs)
2024-04-11 14:24:15 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Shutdown thread)     Stopped ProcessBeneficiary (kafka://NSP.fresh.payment.applicant_sms_logs)
2024-04-11 14:24:16 INFO  [org.apache.camel.impl.engine.AbstractCamelContext] (Shutdown thread) Apache Camel 3.20.1 (camel-2) shutdown in 12s546ms (uptime:1m59s)
2024-04-11 14:24:17 INFO  [io.quarkus] (Shutdown thread) code-with-quarkus stopped in 14.555s
